
import React, { useState } from 'react';
import { 
  ArrowLeftIcon, 
  ClockIcon, 
  CalendarDaysIcon, 
  DocumentDuplicateIcon, 
  SparklesIcon,
  ArrowDownTrayIcon,
  DocumentTextIcon,
  TableCellsIcon,
  CpuChipIcon,
  EyeIcon,
  PencilSquareIcon,
  MagnifyingGlassIcon
} from '@heroicons/react/24/outline';
import { DailyTimesheet, ActivityLog } from '../types';
import { generateTimesheetSummary } from '../services/geminiService';
import { MarkdownRenderer } from './MarkdownRenderer';

interface Props {
  onBack: () => void;
}

// --- MOCK DATA FOR DEMO ---
const MOCK_HISTORY: DailyTimesheet[] = [
  {
    date: 'Today',
    totalHours: 5.2,
    itemsAccessed: 12,
    summary: '', // To be generated by AI
    logs: [
      { id: '1', timestamp: '09:15 AM', resourceName: 'Expert Orion - Delay Analysis Report.pdf', activityType: 'Forensic Analysis', durationMinutes: 45 },
      { id: '2', timestamp: '10:00 AM', resourceName: 'Merged Project Contexts.xlsx', activityType: 'Research', durationMinutes: 120 },
      { id: '3', timestamp: '01:30 PM', resourceName: 'Email Chain - Weather Event.msg', activityType: 'Review', durationMinutes: 15 },
      { id: '4', timestamp: '01:45 PM', resourceName: 'Claim Builder (App)', activityType: 'Drafting', durationMinutes: 90 },
      { id: '5', timestamp: '03:30 PM', resourceName: 'Contract_Main_FIDIC.pdf', activityType: 'Research', durationMinutes: 30 },
      { id: '6', timestamp: '04:00 PM', resourceName: 'Site Photos Folder', activityType: 'Forensic Analysis', durationMinutes: 12 },
    ]
  },
  {
    date: 'Yesterday',
    totalHours: 7.5,
    itemsAccessed: 24,
    summary: 'Focused primarily on the structural steel variation costs. Extensive cross-referencing between the BOQ Spreadsheets and site daily diaries to verify labor hours. Drafted preliminary notice for EOT claim #4.',
    logs: [
      { id: '10', timestamp: '08:30 AM', resourceName: 'BOQ_Rev_04.xlsx', activityType: 'Research', durationMinutes: 180 },
      { id: '11', timestamp: '11:45 AM', resourceName: 'Site Diary May.pdf', activityType: 'Review', durationMinutes: 60 },
      { id: '12', timestamp: '02:00 PM', resourceName: 'Variation_04_Draft.docx', activityType: 'Drafting', durationMinutes: 210 },
    ]
  },
  {
    date: 'Oct 23',
    totalHours: 4.0,
    itemsAccessed: 8,
    summary: 'Initial review of project handover documents. Organized folder structure in Drive and conducted high-level contract review regarding notice periods.',
    logs: []
  },
  {
    date: 'Oct 22',
    totalHours: 6.2,
    itemsAccessed: 15,
    summary: 'Meeting with Client Representative regarding Valuation 5. Updated cash flow forecast spreadsheet based on meeting outcomes.',
    logs: []
  }
];

export const TimesheetDashboard: React.FC<Props> = ({ onBack }) => {
  const [selectedDayIndex, setSelectedDayIndex] = useState(0);
  const [isGenerating, setIsGenerating] = useState(false);
  const [localHistory, setLocalHistory] = useState(MOCK_HISTORY);

  const activeDay = localHistory[selectedDayIndex];

  const handleGenerateSummary = async () => {
    if (activeDay.summary) return; // Already exists
    
    setIsGenerating(true);
    try {
      const summary = await generateTimesheetSummary(activeDay.logs);
      
      // Update local state
      const newHistory = [...localHistory];
      newHistory[selectedDayIndex] = { ...activeDay, summary };
      setLocalHistory(newHistory);

    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  const getActivityColor = (type: string) => {
    switch(type) {
      case 'Forensic Analysis': return 'bg-red-100 text-red-700 border-red-200';
      case 'Drafting': return 'bg-indigo-100 text-indigo-700 border-indigo-200';
      case 'Research': return 'bg-emerald-100 text-emerald-700 border-emerald-200';
      default: return 'bg-slate-100 text-slate-700 border-slate-200';
    }
  };

  const getResourceIcon = (name: string) => {
    if (name.endsWith('.xlsx')) return <TableCellsIcon className="w-4 h-4 text-green-600" />;
    if (name.endsWith('.pdf')) return <DocumentTextIcon className="w-4 h-4 text-red-500" />;
    if (name.includes('App')) return <CpuChipIcon className="w-4 h-4 text-purple-500" />;
    return <DocumentDuplicateIcon className="w-4 h-4 text-slate-400" />;
  };

  return (
    <div className="flex h-screen bg-slate-50 font-sans overflow-hidden">
      
      {/* 1. LEFT SIDEBAR: FILING RECORD */}
      <div className="w-72 bg-white border-r border-slate-200 flex flex-col shrink-0 z-20">
        <div className="p-6 border-b border-slate-100">
           <button onClick={onBack} className="flex items-center text-slate-500 hover:text-indigo-600 mb-6 transition-colors">
              <ArrowLeftIcon className="w-4 h-4 mr-2" /> Back to Hub
           </button>
           <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
              <CalendarDaysIcon className="w-6 h-6 text-indigo-600" />
              Filing Record
           </h2>
           <p className="text-xs text-slate-400 mt-1">Daily consultant activity logs</p>
        </div>

        <div className="flex-1 overflow-y-auto p-4 space-y-2">
           {localHistory.map((day, idx) => (
             <div 
               key={idx}
               onClick={() => setSelectedDayIndex(idx)}
               className={`group p-4 rounded-xl border cursor-pointer transition-all ${
                 selectedDayIndex === idx 
                   ? 'bg-indigo-50 border-indigo-200 shadow-sm' 
                   : 'bg-white border-slate-100 hover:border-indigo-100 hover:shadow-sm'
               }`}
             >
                <div className="flex justify-between items-center mb-2">
                   <span className={`font-bold ${selectedDayIndex === idx ? 'text-indigo-900' : 'text-slate-700'}`}>
                      {day.date}
                   </span>
                   <span className="text-xs font-mono text-slate-400">{day.totalHours}h</span>
                </div>
                <div className="flex items-center gap-2 text-xs text-slate-500">
                   <DocumentDuplicateIcon className="w-3 h-3" />
                   {day.itemsAccessed} items accessed
                </div>
                {/* Visual Progress Bar for Day */}
                <div className="w-full h-1 bg-slate-100 rounded-full mt-3 overflow-hidden">
                   <div 
                     className="h-full bg-indigo-500" 
                     style={{ width: `${Math.min((day.totalHours / 8) * 100, 100)}%` }}
                   ></div>
                </div>
             </div>
           ))}
        </div>
      </div>

      {/* 2. MAIN CONTENT */}
      <div className="flex-1 flex flex-col overflow-hidden bg-slate-50/50">
         
         {/* Top Metrics Bar */}
         <header className="h-20 bg-white border-b border-slate-200 flex items-center px-8 justify-between shrink-0">
            <div>
               <h1 className="text-lg font-bold text-slate-800">Consultant Productivity Report</h1>
               <p className="text-xs text-slate-500">{activeDay.date} • {activeDay.logs.length} Activities Recorded</p>
            </div>
            
            <div className="flex gap-6">
               <div className="flex items-center gap-3 px-4 py-2 bg-slate-50 rounded-lg border border-slate-100">
                  <div className="p-2 bg-indigo-100 text-indigo-600 rounded-md">
                     <ClockIcon className="w-5 h-5" />
                  </div>
                  <div>
                     <p className="text-xs text-slate-500 font-medium">Total Work</p>
                     <p className="text-lg font-bold text-slate-800">{activeDay.totalHours} hrs</p>
                  </div>
               </div>
               
               <div className="flex items-center gap-3 px-4 py-2 bg-slate-50 rounded-lg border border-slate-100">
                  <div className="p-2 bg-emerald-100 text-emerald-600 rounded-md">
                     <MagnifyingGlassIcon className="w-5 h-5" />
                  </div>
                  <div>
                     <p className="text-xs text-slate-500 font-medium">Focus</p>
                     <p className="text-lg font-bold text-slate-800">Research</p>
                  </div>
               </div>

               <button className="flex items-center gap-2 bg-slate-800 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-slate-700 shadow-lg shadow-slate-200">
                  <ArrowDownTrayIcon className="w-4 h-4" /> Export Log
               </button>
            </div>
         </header>

         <main className="flex-1 overflow-y-auto p-8">
            <div className="max-w-5xl mx-auto space-y-8">
               
               {/* SECTION A: CONCLUSION SUMMARY (AI) */}
               <section className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden relative">
                  <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-gradient-to-r from-white to-slate-50">
                     <h3 className="font-bold text-slate-800 flex items-center gap-2">
                        <SparklesIcon className="w-5 h-5 text-purple-500" />
                        Work Conclusion Summary
                     </h3>
                     {!activeDay.summary && (
                        <button 
                           onClick={handleGenerateSummary}
                           disabled={isGenerating}
                           className="text-xs font-bold text-white bg-purple-600 px-3 py-1.5 rounded-full hover:bg-purple-700 flex items-center gap-1 transition-all"
                        >
                           {isGenerating ? 'Analyzing...' : 'Generate Conclusion'}
                        </button>
                     )}
                  </div>
                  
                  <div className="p-8 min-h-[120px]">
                     {activeDay.summary ? (
                        <div className="prose prose-sm max-w-none text-slate-700 leading-relaxed">
                           <MarkdownRenderer content={activeDay.summary} />
                        </div>
                     ) : (
                        <div className="flex flex-col items-center justify-center h-full text-slate-400 py-4">
                           <DocumentTextIcon className="w-12 h-12 mb-2 opacity-20" />
                           <p className="text-sm">No summary generated for this day.</p>
                        </div>
                     )}
                  </div>
               </section>

               {/* SECTION B: DETAILED ACTIVITY BREAKDOWN */}
               <section className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
                  <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                     <h3 className="font-bold text-slate-800">Detailed Activity Register</h3>
                     <div className="flex gap-2">
                        <button className="text-xs font-medium text-slate-500 hover:text-indigo-600 flex items-center gap-1">
                           <EyeIcon className="w-4 h-4" /> Group by File
                        </button>
                        <span className="text-slate-300">|</span>
                        <button className="text-xs font-medium text-indigo-600 flex items-center gap-1">
                           <ClockIcon className="w-4 h-4" /> Chronological
                        </button>
                     </div>
                  </div>

                  <div className="overflow-x-auto">
                     <table className="w-full text-sm text-left">
                        <thead className="bg-slate-50 text-slate-500 uppercase text-xs font-bold">
                           <tr>
                              <th className="px-6 py-4">Time</th>
                              <th className="px-6 py-4">Resource / File Name</th>
                              <th className="px-6 py-4">Activity Type</th>
                              <th className="px-6 py-4 text-right">Duration</th>
                              <th className="px-6 py-4 text-center">Actions</th>
                           </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                           {activeDay.logs.length === 0 ? (
                              <tr>
                                 <td colSpan={5} className="px-6 py-12 text-center text-slate-400 italic">
                                    No detailed logs available for this date.
                                 </td>
                              </tr>
                           ) : (
                              activeDay.logs.map((log) => (
                                 <tr key={log.id} className="hover:bg-slate-50 transition-colors">
                                    <td className="px-6 py-4 font-mono text-slate-500 text-xs">
                                       {log.timestamp}
                                    </td>
                                    <td className="px-6 py-4">
                                       <div className="flex items-center gap-3">
                                          {getResourceIcon(log.resourceName)}
                                          <span className="font-medium text-slate-700">{log.resourceName}</span>
                                       </div>
                                    </td>
                                    <td className="px-6 py-4">
                                       <span className={`text-[10px] px-2 py-1 rounded-full font-bold uppercase tracking-wide border ${getActivityColor(log.activityType)}`}>
                                          {log.activityType}
                                       </span>
                                    </td>
                                    <td className="px-6 py-4 text-right font-mono text-slate-600">
                                       {log.durationMinutes}m
                                    </td>
                                    <td className="px-6 py-4 text-center">
                                       <button className="text-slate-400 hover:text-indigo-600 transition-colors">
                                          <PencilSquareIcon className="w-4 h-4" />
                                       </button>
                                    </td>
                                 </tr>
                              ))
                           )}
                        </tbody>
                        {activeDay.logs.length > 0 && (
                           <tfoot className="bg-slate-50">
                              <tr>
                                 <td colSpan={3} className="px-6 py-4 font-bold text-slate-700 text-right">Total Recorded Duration</td>
                                 <td className="px-6 py-4 text-right font-bold text-indigo-600 text-lg">
                                    {activeDay.logs.reduce((acc, curr) => acc + curr.durationMinutes, 0)}m
                                 </td>
                                 <td></td>
                              </tr>
                           </tfoot>
                        )}
                     </table>
                  </div>
               </section>

            </div>
         </main>

      </div>
    </div>
  );
};
